version: '3.8'

services:
  db-mysql:
    image: mysql:8
#    build:
#      context: ./<cloned-dir>
#      dockerfile: <docker within context>
    volumes:
      - ../mysql:/docker-entrypoint-initdb.d      
    ports:
      - "3306:3306"  
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      

